### PR TITLE
Fix notes

### PR DESCRIPTION
**Pull request by aridf**
This PR is to address the remaining notes in that come up running rcmdcheck or devtools::check(). Feel free to add to this list:

- [ ] Change unregistered s3s to be normal functions.

- [ ] Fix remaining global function/variable issues.

- [ ] Trim imports.

### CODE REVIEW

**Comment by scottyhq** [comment]
thanks @aridf - can you rebase this so that there aren't quite so many commits? will be easier to see what the proposed changes are.

**Comment by pssachdeva** [comment]
I rebased onto master, effectively dropping most of the commits, since they were from previous merges. 

One thing I wasn't sure about is that `ei_rxc.R` looks a lot different from the second commit. @aridf, is this supposed to be there?

The current error is because `ei_rxc.R` and `ei_iter.R` now have different outputs to their `estimates` in the `eiCompare` object. The latter uses `se` and the former uses `se`. So the `rbind` in `plot.eiCompare` is throwing an error. I assume this is due to changes in the `ei_rxc.R`.

**Comment by aridf** [comment]
It looks like `ei_rxc` fell way behind master somewhere in the rebase. It was also missing all of its recent parallelization additions. I just brought it up to do date by replacing it with the code in master and it's now passing locally. Now there's an apparently trivial conflict in the `NAMESPACE`.

**Comment by pssachdeva** [comment]
That's odd. For some reason those removals from `ei_rxc` occur in the "move ei_sim.R and unregistered S3 methods to .Rbuildignore" commit (ff0f672). I'm going to rebase and drop that commit, and add it separately. I think the only thing it should be doing is adding files to the build ignore.

**Comment by pssachdeva** [comment]
Closing this so that we can start with clean commit history.

**Pull request closed without merging**
